"""
HomeworkGrader — uses Claude (claude-sonnet-4-20250514) to grade
homework submissions on three axes:
  1. Completeness  (0-10): Did they answer every part of every question?
  2. Effort        (0-10): Depth, examples, specificity.
  3. Originality   (0-10): Does it read like genuine founder thinking, or pure AI output?

Also generates personalised written feedback for Stage 2.
"""

import re, json, logging
import anthropic

log = logging.getLogger(__name__)

GRADE_SYSTEM = """
You are an expert startup accelerator program director evaluating founder homework submissions.
Respond ONLY with a valid JSON object, no markdown, no preamble.
""".strip()

GRADE_PROMPT = """
Evaluate the following homework submission for a founder in the fi.co accelerator program.

SUBMISSION:
{submission_text}

Rate on three dimensions, each 0-10:
- completeness: Did the founder answer every sub-question fully? 10 = every part answered thoroughly.
- effort: Depth of thought, use of specific examples, research. 10 = exceptional depth.
- originality: Does this reflect personal founder experience and insight, or is it generic AI output?
  10 = clearly personal, specific, and authentic. 2 = almost certainly generated by AI with no personalization.

Also produce:
- strengths: 2-3 bullet points (strings) on what was done well.
- improvements: 2-3 bullet points (strings) on what could be better.
- summary: 1 sentence overall assessment.
- ai_likely: true/false — your best judgment on whether the response is primarily AI-generated.

Respond ONLY with JSON:
{{
  "completeness": <int>,
  "effort": <int>,
  "originality": <int>,
  "total": <int 0-30>,
  "letter_grade": "<A+|A|A-|B+|B|B-|C+|C|D|F>",
  "summary": "<string>",
  "strengths": ["<str>","<str>"],
  "improvements": ["<str>","<str>"],
  "ai_likely": <bool>
}}
"""

FEEDBACK_SYSTEM = """
You are a supportive but honest program director at fi.co, a startup accelerator.
Write directly to the founder by name. Be encouraging but specific.
Do NOT use placeholder brackets. Keep it under 300 words.
""".strip()

FEEDBACK_PROMPT = """
Write personalised homework feedback for {name} (company: {company}).

Grading results:
- Completeness: {completeness}/10
- Effort: {effort}/10
- Originality: {originality}/10
- Letter grade: {letter_grade}
- Summary: {summary}
- Strengths: {strengths}
- Areas to improve: {improvements}
- AI-generated content likely: {ai_likely}

Write 3 short paragraphs:
1. Open with something specific and encouraging.
2. Address the biggest improvement area concretely.
3. Close with a motivating, forward-looking sentence tied to their startup journey.
"""


class HomeworkGrader:
    def __init__(self, api_key: str):
        self.client = anthropic.Anthropic(api_key=api_key)

    def _submission_to_text(self, submission: dict) -> str:
        parts = []
        for k, v in submission.items():
            if k.startswith("q") and not k.startswith("q") == k:
                parts.append(f"Q: {v}")
            elif k.startswith("a"):
                parts.append(f"A: {v}\n")
            elif k == "raw_page_text":
                pass  # skip the giant blob unless no Q/A found
        if not parts:
            parts.append(submission.get("raw_page_text", str(submission))[:4000])
        return "\n".join(parts)

    def grade(self, submission: dict) -> dict:
        text = self._submission_to_text(submission)
        if not text.strip():
            return self._empty_grade()

        prompt = GRADE_PROMPT.format(submission_text=text[:6000])
        try:
            msg = self.client.messages.create(
                model="claude-sonnet-4-20250514",
                max_tokens=800,
                system=GRADE_SYSTEM,
                messages=[{"role": "user", "content": prompt}]
            )
            raw = msg.content[0].text.strip()
            grade = json.loads(raw)
            grade["submitted"] = True
            return grade
        except Exception as e:
            log.error(f"Grading failed: {e}")
            return self._empty_grade(error=str(e))

    def generate_feedback(self, row: dict) -> str:
        prompt = FEEDBACK_PROMPT.format(
            name         = row.get("name", "Founder"),
            company      = row.get("company", "your startup"),
            completeness = row.get("completeness", "N/A"),
            effort       = row.get("effort", "N/A"),
            originality  = row.get("originality", "N/A"),
            letter_grade = row.get("letter_grade", "N/A"),
            summary      = row.get("summary", ""),
            strengths    = "\n  - ".join(row.get("strengths", [])),
            improvements = "\n  - ".join(row.get("improvements", [])),
            ai_likely    = row.get("ai_likely", False),
        )
        msg = self.client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=600,
            system=FEEDBACK_SYSTEM,
            messages=[{"role": "user", "content": prompt}]
        )
        return msg.content[0].text.strip()

    def _empty_grade(self, error: str = "") -> dict:
        return {
            "submitted":    False,
            "completeness": 0,
            "effort":       0,
            "originality":  0,
            "total":        0,
            "letter_grade": "F",
            "summary":      "Not submitted" if not error else f"Error: {error}",
            "strengths":    [],
            "improvements": ["Submit homework"],
            "ai_likely":    False,
        }
